
spring:
  application:
    name: User Activities

  datasource:  
    url: jdbc:postgresql://localhost:5432/useractivities
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        format_sql: false
        
        
  